[project]
name = "bootcamp-matematicas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.8.1",
    "marimo>=0.18.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "sympy>=1.14.0",
]
